services:
  backend:
    build: ./node
    restart: always
    ports:
      - "3000:3000"
    networks:
      - new_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - new_network

networks:
  new_network:
    driver: bridge

volumes:
  new_volume:
    driver: local